# -*- mode: yaml; -*-

---
# file: roles/mirror/defaults/main.yml

mirror:
    # master mirror host name
    masterhost: mirror-master.dragonflybsd.org

    # base directory where the datasets will be synced to
    destdir: /archive

    # OS user
    user: mirror

    # OS group
    group: mirror
